apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        direct: true
    - origin:
        kind: Warehouse
        name: features
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: helm/envs/dev
            - name: argocdApp
              value: kargo-helm-dev

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - dev
    - origin:
        kind: Warehouse
        name: features
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: helm/envs/test
            - name: argocdApp
              value: kargo-helm-test

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: cert
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - test
    - origin:
        kind: Warehouse
        name: features
      sources:
        stages:
          - test
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: helm/envs/cert
            - name: argocdApp
              value: kargo-helm-cert

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - cert
    - origin:
        kind: Warehouse
        name: features
      sources:
        stages:
          - cert
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: helm/envs/prod
            - name: argocdApp
              value: kargo-helm-prod

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-child-1
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - cert
    - origin:
        kind: Warehouse
        name: features
      sources:
        stages:
          - cert
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: helm/envs/prod-child-1
            - name: argocdApp
              value: kargo-helm-prod-child-1
